### ISSUE TITLE
(Trouver puis) afficher une forme approximative de la France sur une page web (en SVG par exemple)

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/diaphane#1]

**Comment by DavidBruant** [comment]
Accorder le système de coordonnées avec #2 va être compliqué. Autant passer par leaflet/mapbox directement

**Comment by bleucitron** [comment]
Je poste ça ici juste pour documenter:
Il y a les contours des régions/départements/communes et d'autres [ici](https://www.data.gouv.fr/fr/datasets/contours-des-regions-francaises-sur-openstreetmap/)

Il y a aussi des svgs pour les régions/départements, mais pas pour les communes.
